#!/usr/bin/env sh

USER="alex"
HOST="wall-e"
NAME="cfw"
ARCH="thumbv7em-none-eabihf"
MCU="TEENSY41"

OUTPUT_DIR="./target/$ARCH/release"
OUTPUT_PATH="$OUTPUT_DIR/$NAME.hex"

REMOTE_DIR="/tmp/teensy-load"
REMOTE_PATH="$REMOTE_DIR/$NAME.hex"

TTY_DIR="/dev"
TTY_PATH="$TTY_DIR/ttyACM0"

cargo objcopy --release -- -O ihex "$OUTPUT_PATH"
ssh "$USER@$HOST" mkdir -p "$REMOTE_DIR" &&
scp "$OUTPUT_PATH" "$USER@$HOST:$REMOTE_PATH" &&

echo -e "\nRunning"
ssh "$USER@$HOST" teensy_loader_cli --mcu="$MCU" -w "$REMOTE_PATH" &&
ssh "$USER@$HOST" "inotifywait -qqe create \"$TTY_DIR\" && cat \"$TTY_PATH\""
